#!/bin/bash
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin


#PATH=$PATH:/usr/local/bin

DIR=`date +%Y-%m-%d`
#DATE=`date +"%Y%m%d"`
MYSQL='mysql --skip-column-names'
destination="/mnt/backup/mysql"
db_name="SHOW DATABASES LIKE '%'"
s='glpi'
mysql -e 'stop replica;'


mkdir $destination/$DIR

#for s in mysql `$MYSQL -e "$db_name"`;
#    do
mkdir $destination/$DIR/$s;
/usr/bin/mysqldump --set-gtid-purged=OFF $s > $destination/$DIR/$s/$s.sql;
#        done
                echo "База $s скопирована"


#for s in mysql `$MYSQL -e "SHOW DATABASES LIKE '%\_db'"`;
#    do
#        mkdir $s;
#        /usr/bin/mysqldump --add-drop-table --add-locks --create-options --disable-keys --extended-insert --single-transaction --quick --set-charset --events --routines --triggers  $s | gzip -1 > $s/$s.gz;
#    done


 
#destination="/mnt/backup/mysql"
#userDB="relp"
#passwordDB="Otus1Repl2!"
#fdate=`date +%Y-%m-%d`
# mysql -e 'stop replica;'
#find $destination -type d \( -name "*-1[^5]" -o -name "*-[023]?" \) -mtime +30 -exec rm -R {} \; 2>&1
#find $destination -type d -name "*-*" -mtime +180 -exec rm -R {} \; 2>&1
#test -d $destination/$fdate || mkdir -p $destination/$fdate 
#for dbname in `echo show databases | mysql -u$userDB -p$passwordDB | grep -v Database`; do
#    case $dbname in
#        information_schema)
#            continue ;;
#        mysql)
#            continue ;;
#        performance_schema)
#            continue ;;
#        test)
#            continue ;;
#        sys)
#            continue ;;
#        *) mysqldump --databases --skip-comments --no-tablespaces -u$userDB -p$passwordDB $dbname | gzip > $destination/$fdate/$dbname.sql.gz ;;
#    esac
#done;
mysql -e 'start replica;'