---
- name: Include custom MySQL configuration
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart MySQL service


  
- name: Create replication user for master
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    state: present

- name: Fetch MySQL master status
  mysql_replication:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    mode: "getprimary"
  register: mysql_master_status

- include_role:
    name: mysql_slave
  vars:
    mysql_master_status: "{{ mysql_master_status }}"
  

- name: Log MySQL master status
  debug:
    var: mysql_master_status
  when: mysql_master_status is defined

- name: Create a glpi database
  mysql_db: 
    name: glpi
    state: present
    collation: utf8_general_ci
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create glpi user
  mysql_user:
    name: glpi
    password: "{{ glpi_pass }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "%"
    priv: 
      'glpi.*': 'ALL,GRANT'
    state: present
  notify: Restart MySQL service

...